### PR TITLE
Rewrite admin panel

### PR DESCRIPTION
**Pull request by flokX**
In this PR the base of the admin panel is rewritten. The primary change is to use vue.js. The result is that the interaction methods are better structured with Vue than before. The charts are organised as a components.

Some changes;
* Most interactions controlled by Vue
* Charts as Vue components
* Remove shortlink names filter

### CODE REVIEW

**Comment by guzzisti** [comment]
I've deployed the admin panel to my site and like to provide some feedback.

I quite like the redesign, especially that that the original link is now shown and the delete button is more obvious. The 7day & total summary above the chart is a nice addition and shows the correct values.
The charts need some polishing: the bars have the wrong size and the mouse-over shows different, but as well wrong values.

In my opinion the previously used "frappe charts" where a better solution to get on overview of the usage than the bar charts are. The charts don't work out well when zoomed out to a larger timespan like, e.g. months. But that
If you by chance use the mouse wheel while the pointer is over a chart, it's adjusts the charts timerange instead of scrolling.
This is for sure an issue of liking. Maybe the usage can be improved a bit by providing additional pre-selections like "last quarter", "last 6 month" and "last year".

**Comment by guzzisti** [comment]
Update: The totals above the seems to be correct for the last 7 days, but not the overall total (e.g. last 7 days shows 200 accesses and overall total shows 2 accesses).

**Comment by guzzisti** [comment]
The charts look good now. :+1:

**Comment by flokX** [comment]
Thanks for your error reports, I fixed them.

I wanted to replace the frappe-charts library with chart.js for a couple of reasons: Responsive charts, better comparison between two dates and an actively maintained library (the status of frappe-charts is not really clear). I had a prototype before and it looked good.

Now I deployed it to my installation and I have to agree with you. In installations with many shortlinks the admin page becomes confusing. The most important point for me is the fact that devShort should be an URL shortener for developers with a small amount of shortlinks with moderate traffic. For those, the heatmap charts are clearer and you can get a better overview.

I created a new branch where I removed chart.js. Please have a look at it and give me feedback.

**Comment by guzzisti** [comment]
Jep, i definitely prefer the heatmap-style of the frappe-charts, they give a good overview. I don't need advanced features like zooming for the charts.

**Comment by guzzisti** [comment]
There's a CORS error when opening the admin site, but everything else is now working fine and ready to be merged from my point of view.

image

**Comment by flokX** [comment]
> There's a CORS error when opening the admin site

I can't reproduce your error, in my local test setup and in my hosting environment everything works fine in Chrome, Firefox and Edge. I use them on Windows. I changed a few things at the api-endpoint, if the problem persists please open an issue (the version checker was introduced in the PR #12).

Beside that this PR should be finished, please notice when you test it that the keys in the stats.json file are now according to the ISO standard to provide a better readability.

**Comment by guzzisti** [comment]
hm, the CORS error is gone now...no clue why it popped up yesterday.

Gonna test the latest changes later this evening.

**Comment by guzzisti** [comment]
Found some time do deploy and test a bit:
Every time you hit "Reload charts" the totals above the charts are increased by to original values. Seems there's some kind of initialization missing.

I'm not sure if the following behaviour is intentional:
I kept my old `stats.json` , new accesses to short-URLs are logged now using the new date-format. The charts in the admin-panel only show the values of the old timestamp-format as long as one if this kind is there. When only date-formatted values are there, these are shown in the charts.

**Comment by flokX** [comment]
I saw this behavior with two time formats, too. Maybe it's somehow connected to the internals of the frappe-charts library. In my opinion it doesn't matter, we have a new version with breaking changes and I will provide a conversion tool for old stats.json files.

Thanks again for your testing and feedback!

**Pull request merged**
